version: "3.5"
services:
  server:
    container_name: backend
    image: backend
    build: .
    ports:
      - "8080:80"
    networks:
      - db
    env_file:
      - variables.env
    depends_on:
      - api-postgres
  api-postgres:
    container_name: api-database
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=api
      - POSTGRES_USER=admin
    networks:
      - db
    volumes:
      - /var/ticket_manager/postgres:/var/lib/postgresql/data
networks:
  db:
    name: db
    driver: bridge
