version: "3.5"
services:
  server:
    container_name: backend
    image: backend
    build:
      context: .
      dockerfile: Dockerfile.core
    ports:
      - "8080:80"
    networks:
      - db
      - pay
      - rabbit
    env_file:
      - variables.env
    depends_on:
      - api-postgres
      - payment-service
      - rabbitmq
      - pdf-generator
  api-postgres:
    container_name: api-database
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=api
      - POSTGRES_USER=admin
    networks:
      - db
    volumes:
      - /var/ticket_manager/postgres:/var/lib/postgresql/data
  payment-service:
    container_name: payment-service
    image: payment-service
    build:
      context: .
      dockerfile: Dockerfile.payment
    ports:
      - "8081:80"
    networks:
      - pay
    env_file:
      - variables.env
  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbit
  pdf-generator:
    container_name: pdf-generator
    image: pdf-generator
    build:
      context: .
      dockerfile: Dockerfile.pdf_generator
    networks:
      - rabbit
    env_file:
      - variables.env
    depends_on:
      - rabbitmq
networks:
  db:
    name: db
    driver: bridge
  pay:
    name: pay
    driver: bridge
  rabbit:
    name: rabbit
    driver: bridge
