# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Back-end build and test

on:
  pull_request:
    branches:
      - 'master'
      - 'dev'
  push:
    branches: 
      - 'master'
      - 'dev'
      - 'feature/*'
      - 'fix/*'
      - 'hotfix/*'
    paths:
      - 'src/back/*'
  workflow_dispatch:
  
jobs:
  build:
    name: Build and test backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/back/TicketManager
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/Core/TicketManager.Core.Api/TicketManager.Core.Api.csproj
    - name: Build
      run: dotnet build src/Core/TicketManager.Core.Api/TicketManager.Core.Api.csproj --no-restore
    - name: Test Domain Tests
      run: dotnet test tests/Core/TicketManager.Core.DomainTests/TicketManager.Core.DomainTests.csproj --no-build --verbosity normal
    - name: Test Services Tests
      run: dotnet test tests/Core/TicketManager.Core.ServicesTests/TicketManager.Core.ServicesTests.csproj --no-build --verbosity normal
    - name: Test Integration Tests
      run: dotnet test tests/TicketManager.IntegrationTests/TicketManager.Core.IntegrationTests.csproj --no-build --verbosity normal
