name: Front-end - Test application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/front/ticketer
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
          architecture: x64
      - name: Check version of flutter
        run: flutter --version
      - name: Update dependencies
        run: flutter pub get
      - name: Test app
        run: flutter test
