
name: ci_build_flutter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./src/front/ticketer
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
          architecture: x64
      - run: |
          echo CHANNEL=${{ steps.flutter-action.outputs.CHANNEL }}
          echo VERSION=${{ steps.flutter-action.outputs.VERSION }}
          echo ARCHITECTURE=${{ steps.flutter-action.outputs.ARCHITECTURE }}
        shell: bash
      - name: Check version of flutter
        run: flutter --version
      - name: Update dependencies
        run: flutter pub get
      # We do not have any tests yet so we leave out this step
      # - name: Test app
      #   run: flutter test
      - name: Build Android app
        run: |
          flutter build apk
          flutter build appbundle
      - name: Build iOS app
        run: lutter build ios --release --no-codesign
      - name: Build web app
        run: flutter build web
