name: Front-end - Build Web

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types: [ "labeled" ]

  workflow_dispatch:

jobs:
  build:
    if: github.event.label.name == 'front-end-build' || github.ref == 'refs/heads/master'
    name: Build front-end Web application
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/front/ticketer
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
      - name: Check version of flutter
        run: flutter --version
      - name: Update dependencies
        run: flutter pub get
      - name: Test app
        run: flutter test
      - name: Build web app
        run: flutter build web
      - name: Save web build
        uses: actions/upload-artifact@v3
        with:
          name: release-web-build
          retention-days: 1
          path: ./src/front/ticketer/build/web/
