
name: ci_build_flutter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types: [ "labeled" ]

  workflow_dispatch:

jobs:
  build:
    if: github.event.label.name == 'front-end-build' || github.ref == 'refs/heads/master'
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./src/front/ticketer
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
          architecture: x64
      - name: Check version of flutter
        run: flutter --version
      - name: Update dependencies
        run: flutter pub get
      - name: Test app
        run: flutter test
      - name: Build Android app
        run: |
          flutter build apk
          flutter build appbundle
      - name: Build iOS app
        run: flutter build ios --release --no-codesign
      - name: Build web app
        run: flutter build web
